name: Run MATLAB Build on GitHub-Hosted Runner
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - uses: fastai/workflows/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: id_ecdsa
  #     - uses: actions/checkout@v2
  #     - run: source script-linux.sh
  
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@master
